#!/usr/bin/env php
<?php
require_once __DIR__.'/vendor/autoload.php';

$app = new \Cilex\Application('kServer', '1.0');
$app->register(new \Cilex\Provider\ConfigServiceProvider(), array('config.path' => __DIR__."/config/config.yml"));
$app->register(new \Kunstmaan\kServer\Provider\FileSystemProvider());
$app->register(new \Kunstmaan\kServer\Provider\ProcessProvider());
$app->register(new \Kunstmaan\kServer\Provider\SkeletonProvider());
$app->register(new \Kunstmaan\kServer\Provider\ProjectConfigProvider());
$app->register(new \Kunstmaan\kServer\Provider\PermissionsProvider());
$app->register(new \Cilex\Provider\TwigServiceProvider(), array(
    'twig.path' => __DIR__.'/templates',
));
$app->command(new \Kunstmaan\kServer\Command\NewProjectCommand());
$app->command(new \Kunstmaan\kServer\Command\SetPermissionsCommand());
$app->command(new \Kunstmaan\kServer\Command\MaintenanceCommand());
$app->command(new \Kunstmaan\kServer\Command\BackupCommand());
$app->command(new \Kunstmaan\kServer\Command\RemoveProjectCommand());
$app->command(new \Kunstmaan\kServer\Command\ApplySkeletonCommand());

$app->run();
