#!/usr/bin/env php
<?php
require_once __DIR__.'/vendor/autoload.php';


$app = new \Cilex\Application('kServer');
$app->register(new \Cilex\Provider\ConfigServiceProvider(), array('config.path' => __DIR__."/config/config.yml"));
$app->register(new \Kunstmaan\kServer\Provider\FileSystemProvider());
$app->register(new \Kunstmaan\kServer\Provider\ProcessProvider());
$app->register(new \Kunstmaan\kServer\Provider\SkeletonProvider());
$app->register(new \Kunstmaan\kServer\Provider\ProjectConfigProvider());
$app->command(new \Kunstmaan\kServer\Command\NewProjectCommand());
$app->run();
