#!/usr/bin/env php
<?php
require_once __DIR__.'/vendor/autoload.php';

$app = new \Cilex\Application('kServer', '1.0');

$output = new Symfony\Component\Console\Output\ConsoleOutput();

$app->register(new \Cilex\Provider\ConfigServiceProvider(), array('config.path' => __DIR__."/config/config.yml"));
$app->register(new \Kunstmaan\kServer\Provider\FileSystemProvider());
$app->register(new \Kunstmaan\kServer\Provider\ProcessProvider());
$app->register(new \Kunstmaan\kServer\Provider\SkeletonProvider());
$app->register(new \Kunstmaan\kServer\Provider\ProjectConfigProvider());
$app->register(new \Kunstmaan\kServer\Provider\PermissionsProvider());
$app->register(new \Kunstmaan\kServer\Provider\DialogProvider($output));
$app->register(new \Cilex\Provider\TwigServiceProvider(), array(
    'twig.path' => '/',
));


$app->command(new \Kunstmaan\kServer\Command\NewProjectCommand($output));
$app->command(new \Kunstmaan\kServer\Command\SetPermissionsCommand($output));
$app->command(new \Kunstmaan\kServer\Command\MaintenanceCommand($output));
$app->command(new \Kunstmaan\kServer\Command\BackupCommand($output));
$app->command(new \Kunstmaan\kServer\Command\RemoveProjectCommand($output));
$app->command(new \Kunstmaan\kServer\Command\ApplySkeletonCommand($output));

$app->run();
