kserver:
    dependencies:
        base: Kunstmaan\kServer\Skeleton\BaseSkeleton
    name: NAME
    permissions:
        root:
            path: /
            ownership: '-R NAME.NAME'
            acl:
                - '-R -m user::rwx'
                - '-R -m group::---'
                - '-R -m other::---'
        ssh:
            path: /.ssh
            ownership: '-R NAME.NAME'
            acl:
                - '-R -m user::rwX'
                - '-R -m group::---'
                - '-R -m other::---'
                - '-R -m m::---'
    backup:
        excluded: null
