kserver:


    backup:
        excluded: ~

    permissions:
        - root:
            path:       "/"
            ownership:  "-R $superuser.$group"
            acl:
                - "-R -m user::rw-"
                - "-R -m group::---"
                - "-R -m other::---"