projects:
    path:       "/var/www"
    backuppath: "/var/backup"

permissions:
    develmode:  false

mysql:
    rootuser: root
    rootpassword: vagrant

skeletons:
    base:   Kunstmaan\kServer\Skeleton\BaseSkeleton
    mysql:  Kunstmaan\kServer\Skeleton\MySQLSkeleton