projects:
    path:       "/var/www"
    backuppath: "/var/backup"

permissions:
    develmode:  false

mysql:
    rootuser: root
    rootpassword: vagrant

apache:
    serveradmin: support@kunstmaan.be

skeletons:
    base:   Kunstmaan\kServer\Skeleton\BaseSkeleton
    mysql:  Kunstmaan\kServer\Skeleton\MySQLSkeleton
    apache: Kunstmaan\kServer\Skeleton\ApacheSkeleton